export const topographyServiceSlugs = new Set([
  "topografia-convencional-y-automatizada",
  "control-geometrico-de-obras",
  "geodesia-satelital-gnss-rtk",
  "escaneo-laser-3d-lidar-terrestre",
  "fotogrametria-con-drones-uav",
  "batimetria",
  "topografia-para-redes-de-agua-desague-y-energia",
  "perfiles-longitudinales-y-secciones-transversales",
  "levantamientos-para-carreteras-puentes-y-tuneles",
  "levantamiento-catastral-urbano-y-rural",
  "catastro-municipal",
  "saneamiento-fisico-legal-de-predios",
  "independizacion-y-acumulacion-de-predios",
  "peritaje-topografico-legal",
  "topografia-para-infraestructura-agroindustrial",
  "topografia-para-proyectos-de-irrigacion-y-canales",
  "levantamiento-y-marcacion-de-concesiones-mineras",
  "cubicacion-de-tajos-abiertos-y-labores-subterraneas",
  "control-de-voladuras-y-movimiento-de-material",
  "monitoreo-geodesico-de-presas-de-relaves",
  "monitoreo-de-taludes-y-subsidencias",
  "cubicacion-y-movimiento-de-tierras",
]);

export const serviceCategoryBySlug: Record<string, string> = {
  "topografia-convencional-y-automatizada": "Levantamientos y geodesia",
  "geodesia-satelital-gnss-rtk": "Levantamientos y geodesia",
  "batimetria": "Levantamientos y geodesia",
  "control-geometrico-de-obras": "Obra y replanteo",
  "topografia-para-redes-de-agua-desague-y-energia": "Obra e infraestructura",
  "perfiles-longitudinales-y-secciones-transversales": "Obra e infraestructura",
  "levantamientos-para-carreteras-puentes-y-tuneles": "Obra e infraestructura",
  "escaneo-laser-3d-lidar-terrestre": "Escaneo 3D y drones",
  "fotogrametria-con-drones-uav": "Escaneo 3D y drones",
  "levantamiento-catastral-urbano-y-rural": "Catastro y saneamiento",
  "catastro-municipal": "Catastro y saneamiento",
  "saneamiento-fisico-legal-de-predios": "Catastro y saneamiento",
  "independizacion-y-acumulacion-de-predios": "Catastro y saneamiento",
  "peritaje-topografico-legal": "Catastro y saneamiento",
  "topografia-para-infraestructura-agroindustrial": "Topografia sectorial",
  "topografia-para-proyectos-de-irrigacion-y-canales": "Topografia sectorial",
  "levantamiento-y-marcacion-de-concesiones-mineras": "Mineria y movimientos",
  "cubicacion-de-tajos-abiertos-y-labores-subterraneas": "Mineria y movimientos",
  "control-de-voladuras-y-movimiento-de-material": "Mineria y movimientos",
  "monitoreo-geodesico-de-presas-de-relaves": "Monitoreo y control",
  "monitoreo-de-taludes-y-subsidencias": "Monitoreo y control",
  "cubicacion-y-movimiento-de-tierras": "Mineria y movimientos",
};

export const categoryOrder = [
  "Levantamientos y geodesia",
  "Obra y replanteo",
  "Obra e infraestructura",
  "Escaneo 3D y drones",
  "Catastro y saneamiento",
  "Mineria y movimientos",
  "Monitoreo y control",
  "Topografia sectorial",
];
